# Generated by Django 4.1.3 on 2022-11-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('onderwerp', models.CharField(max_length=255)),
                ('bericht', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'contactdata',
                'managed': False,
            },
        ),
    ]
